"""Remote-access products, generated from the LOLRMM catalogue.

DO NOT EDIT BY HAND. Regenerate with:

    python3 tools/sync_signatures.py

Hand-written signatures in signatures.py take precedence; this file
widens the net rather than replacing judgement. Being listed here
means a product exists and is known to be abused, never that its
presence is proof of anything — most entries are legitimate software
someone may have installed deliberately.
"""

# 217 products
CATALOGUE_SIZE = 217

# process name -> product
CATALOGUE_EXECUTABLES = {
    "aa_v3": "Ammyy Admin",
    "action1_agent": "Action1",
    "action1_connector": "Action1",
    "action1_remote": "Action1",
    "action1_update": "Action1",
    "agent": "Monitic",
    "agent-installer-any": "HeartbeatRM",
    "agentinstaller.dll": "Freshservice",
    "agentmon": "Kaseya (VSA)",
    "alpemix": "Alpemix",
    "amon": "Monitic",
    "anydesk": "AnyDesk",
    "anyviewer": "AnyViewer",
    "appcore": "GoToMyPC",
    "aspia_client": "Aspia",
    "ateraagent": "Atera",
    "autoupdate": "Freshservice",
    "avcore": "AnyViewer",
    "bma": "baramundi Management Suite",
    "clboot32": "VIZOR",
    "cldist32": "VIZOR",
    "cldistsvc": "VIZOR",
    "clm": "Teramind",
    "clmeter32": "VIZOR",
    "clmetersvc": "VIZOR",
    "closeapp": "VIZOR",
    "cloudwksinstall": "Faronics Deep Freeze",
    "coreagentservice": "Faronics Core",
    "cpuchk": "VIZOR",
    "dashboard-windows-amd64": "Nezha",
    "dataplicity": "Dataplicity",
    "dephlp": "InvGate",
    "dfc": "Faronics Deep Freeze",
    "dfserv": "Faronics Deep Freeze",
    "dfservex": "Faronics Deep Freeze",
    "dfstd": "Faronics Deep Freeze",
    "dfstdinstall": "Faronics Deep Freeze",
    "dfwks": "Faronics Deep Freeze",
    "docconnect.agent": "TrustConnect",
    "duet": "Duet Display",
    "duetdisp": "Duet Display",
    "duetsetup": "Duet Display",
    "dwm": "Teramind",
    "faronicscoreagent": "Faronics Core",
    "faronicsdeployagent": "Faronics Deploy",
    "faronicssa": "Faronics Deploy",
    "fcaforstartupmonitor.msi": "Faronics Core",
    "fd_agent.dll": "FleetDeck.io",
    "fistudentagent": "Faronics Insight",
    "fistudentsvc": "Faronics Insight",
    "fistudentui": "Faronics Insight",
    "fleetdeck-agent": "FleetDeck.io",
    "fleetdeck-agent.msi": "FleetDeck.io",
    "fleetdeck_agent_svc": "FleetDeck.io",
    "fleetdeck_installer": "FleetDeck.io",
    "frcserver": "Faronics Deploy",
    "freshservice.discoveryprobe.autoflush": "Freshservice",
    "freshservice.discoveryprobe.oidlibrarypuller": "Freshservice",
    "freshservice.discoveryprobe.progressbar": "Freshservice",
    "freshservice.discoveryprobe.scanservice": "Freshservice",
    "freshservice.discoveryprobe.window": "Freshservice",
    "fsagentautoupdate": "Freshservice",
    "fsagentcrashstatusupdater": "Freshservice",
    "fsagentservice": "Freshservice",
    "fsprobecrashstatusupdater": "Freshservice",
    "fsprobereporter": "Freshservice",
    "fsscheduler": "Freshservice",
    "fssinstaller": "Faronics Deploy",
    "fswmiscanner": "Freshservice",
    "fwa_ui_agent": "Faronics Deploy",
    "fwaservice": "Faronics Deploy",
    "g2comm": "GoToMyPC",
    "g2fileh": "GoToMyPC",
    "g2host": "GoToMyPC",
    "g2m": "GoToMyPC",
    "g2m_download": "GoToMyPC",
    "g2mainh": "GoToMyPC",
    "g2mchat": "GoToMyPC",
    "g2mcodecinstextractor": "GoToMyPC",
    "g2mcomm": "GoToMyPC",
    "g2mcoreinstextractor": "GoToMyPC",
    "g2mfeedback": "GoToMyPC",
    "g2mhost.exee": "GoToMyPC",
    "g2minstaller": "GoToMyPC",
    "g2minstallerextractor": "GoToMyPC",
    "g2minsthigh": "GoToMyPC",
    "g2mlauncher": "GoToMyPC",
    "g2mmatchmaking": "GoToMyPC",
    "g2mmaterials": "GoToMyPC",
    "g2mpolling": "GoToMyPC",
    "g2mqanda": "GoToMyPC",
    "g2mrecorder": "GoToMyPC",
    "g2mscrutil64": "GoToMyPC",
    "g2msessioncontrol": "GoToMyPC",
    "g2mstart": "GoToMyPC",
    "g2mtesting": "GoToMyPC",
    "g2mtranscoder": "GoToMyPC",
    "g2mui": "GoToMyPC",
    "g2muninstall": "GoToMyPC",
    "g2mupload": "GoToMyPC",
    "g2mvideoconference": "GoToMyPC",
    "g2mview": "GoToMyPC",
    "g2printh": "GoToMyPC",
    "g2quick": "GoToMyPC",
    "g2svc": "GoToMyPC",
    "g2tray": "GoToMyPC",
    "getscreen": "GetScreen",
    "glpi-agent": "GLPI Agent",
    "glpi-esx": "GLPI Agent",
    "glpi-injector": "GLPI Agent",
    "glpi-inventory": "GLPI Agent",
    "glpi-netdiscovery": "GLPI Agent",
    "glpi-netinventory": "GLPI Agent",
    "glpi-remote": "GLPI Agent",
    "glpi-win32-service": "GLPI Agent",
    "gopcsrv": "GoToMyPC",
    "gorelo.rmm.setup": "Gorelo RMM",
    "goto": "GoToMyPC",
    "gotoscrutils": "GoToMyPC",
    "hbrm-updater-x64": "HeartbeatRM",
    "hbrm-x64": "HeartbeatRM",
    "helpwire": "HelpWire",
    "hoptodesk": "HopToDesk",
    "httpget": "VIZOR",
    "httppush": "VIZOR",
    "id_tray": "iDrive",
    "idcomponent.dll": "iDrive",
    "idriveeclassic": "iDrive",
    "idrivewinsetup": "iDrive",
    "immyagent": "ImmyBot",
    "immybot.agent.ephemeral": "ImmyBot",
    "immybot.msi": "ImmyBot",
    "immyupdater": "ImmyBot",
    "insightinstaller": "Faronics Insight",
    "insightinstallerstudent": "Faronics Insight",
    "insightinstallerteacher": "Faronics Insight",
    "installcore": "RemotePulse",
    "invgate-ed": "InvGate",
    "invgateassetsrd": "InvGate",
    "invgaterd": "InvGate",
    "iprangecalculator": "Freshservice",
    "kaupdhlp": "Kaseya (VSA)",
    "kausrtsk": "Kaseya (VSA)",
    "komari": "Komari",
    "komari-agent": "Komari",
    "level": "Level",
    "lmiguardiansvc": "LogMeIn",
    "lmiignition": "LogMeIn",
    "loclx": "LocalXpose",
    "logmein": "LogMeIn",
    "logmeinsystray": "LogMeIn",
    "luedit": "VIZOR",
    "luguard": "VIZOR",
    "lulogon": "VIZOR",
    "lunixar": "Lunixar",
    "lusmbios32": "VIZOR",
    "lutinfow32": "VIZOR",
    "manageengine_servicedesk_plus": "ManageEngine ServiceDesk Plus",
    "manageengine_servicedesk_plus.bin": "ManageEngine ServiceDesk Plus",
    "meshagent": "MeshCentral",
    "modulesupgrademgr": "Faronics Deploy",
    "moniticinstaller": "Monitic",
    "mousewithoutborders": "Mouse Without Borders",
    "mqmailintegration": "VIZOR",
    "mstsc": "mstsc.exe (Microsoft Remote Desktop Connection)",
    "netbird": "NetBird",
    "netbird-ui": "NetBird",
    "netbird_installer": "NetBird",
    "nezha-agent": "Nezha",
    "niniteone": "Ninite Pro (Ninite Agent)",
    "notificationhelper": "Faronics Deploy",
    "nuke32": "VIZOR",
    "nvda": "NVDA (Non-Visual Desktop Access)",
    "nvda_service": "NVDA (Non-Visual Desktop Access)",
    "parsecd": "Parsec",
    "pidupdater": "VIZOR",
    "pitunnel": "PiTunnel",
    "plink": "Freshservice",
    "prep64": "VIZOR",
    "radmin": "RAdmin",
    "rcclient": "AnyViewer",
    "rcservice": "AnyViewer",
    "recycler": "VIZOR",
    "regapps": "VIZOR",
    "remcmdstub": "NetSupport Manager",
    "remotedesktopmanager": "Devolutions Remote Desktop Manager",
    "remotely_agent": "Remotely",
    "remotely_desktop": "Remotely",
    "remsupp": "RemSupp",
    "remsupp_setup_x64": "RemSupp",
    "rodexagent": "Rodex RMM",
    "rserver3": "RAdmin",
    "screancap": "AnyViewer",
    "selfupdater": "VIZOR",
    "setup": "VIZOR",
    "shellhub-agent": "ShellHub",
    "si": "TiFLUX",
    "stahelper": "Faronics Insight",
    "statementview.msi": "Miradore",
    "studentsvc": "Faronics Insight",
    "supremosystem": "Supremo",
    "teamviewer": "TeamViewer",
    "teramind-remover": "Teramind",
    "teramind.remover.executable": "Teramind",
    "teramind.setup.remover": "Teramind",
    "teramind.setup.ui": "Teramind",
    "teramind.setup.uiarm": "Teramind",
    "teramind.setup.updater": "Teramind",
    "tiagent": "TiFLUX",
    "tiservice": "TiFLUX",
    "tiupdateservice": "TiFLUX",
    "tmagentsvc": "Teramind",
    "tmate": "tmate",
    "trustconnectagent": "TrustConnect",
    "trustconnectagent.dll": "TrustConnect",
    "uninstallstatusupdater": "Freshservice",
    "update-shim": "Teramind",
    "upload": "VIZOR",
    "vecwait": "VIZOR",
    "vnconfigutils": "VIZOR",
    "vnldriverinstaller": "VIZOR",
    "vnlselfupdate": "VIZOR",
    "wesvc": "Controlio",
    "winchk32": "VIZOR",
    "wintun.dll": "NetBird",
}

# product -> domains its own infrastructure uses
CATALOGUE_DOMAINS = {
    "247ithelp.com (ConnectWise)": ("247ithelp.com",),
    "Absolute (Computrace)": ("absolute.com", "namequery.com",),
    "Acronis Cyber Protect (Remotix)": ("acronis.com", "remotix.com",),
    "Action1": ("action1.com", "amazonaws.com",),
    "Addigy": ("addigy.com",),
    "Adobe Connect": ("adobeconnect.com",),
    "AeroAdmin": ("aeroadmin.com",),
    "AliWangWang-remote-control": ("taobao.com",),
    "Alpemix": ("alpemix.com", "teknopars.com",),
    "Ammyy Admin": ("ammyy.com",),
    "Any Support": ("anysupport.net",),
    "AnyDesk": ("anydesk.com",),
    "AnyViewer": ("anyviewer.com", "aomeisoftware.com",),
    "Anyplace Control": ("anyplace-control.com",),
    "Atera": ("atera.com", "getalphacontrol.com", "pubnubapi.com", "windows.net",),
    "Auvik": ("auvik.com",),
    "AweRay": ("aweray.com",),
    "Barracuda": ("barracudamsp.com", "islonline.net",),
    "Basecamp": ("basecamp.com",),
    "BeAnyWhere": ("beanywhere.com",),
    "BeInSync": ("beinsync.com", "beinsync.net",),
    "BeamYourScreen": ("beamyourscreen.com",),
    "BeyondTrust (Bomgar)": ("beyondtrustcloud.com", "bomgarcloud.com",),
    "Bluetrait": ("bluetrait.io",),
    "CentraStage (Now Datto)": ("centrastage.net", "datto.com",),
    "Centurion": ("centuriontech.com",),
    "Chrome Remote Desktop": ("google.com", "googleapis.com",),
    "Comodo RMM": ("comodo.com",),
    "ConnectWise Control": ("connectwise.com", "screenconnect.com",),
    "Connectwise Automate (LabTech)": ("hostedrmm.com",),
    "CrossLoop": ("crossloop.com", "softonic.com",),
    "DW Service": ("dwservice.net",),
    "DameWare": ("dameware.com",),
    "Dataplicity": ("dataplicity.com",),
    "DeskDay": ("deskday.ai",),
    "DesktopNow": ("nchuser.com",),
    "Distant Desktop": ("distantdesktop.com", "signalserver.xyz",),
    "Domotz": ("domotz.co", "domotz.com",),
    "Duet Display": ("duetdisplay.com", "itagent.com",),
    "EMCO Remote Console": ("emcosoftware.com",),
    "Electric AI (Kaseya)": ("electric.ai",),
    "Encapto": ("encapto.com",),
    "Ericom AccessNow": ("ericom.com",),
    "Ericom Connect": ("ericom.com",),
    "Faronics Core": ("faronics.com", "faronicslabs.com",),
    "Faronics Deep Freeze": ("deepfreeze.com", "faronics.com", "faronicscloud.com", "faronicslabs.com",),
    "Faronics Deploy": ("amazonaws.com", "faronics.com", "faronicscloud.com", "faronicsdeploy.com", "faronicslabs.com",),
    "Faronics Insight": ("faronics.com",),
    "FastViewer": ("fastviewer.com",),
    "FixMe.it": ("fixme.it", "set.me", "setme.net", "techinline.net",),
    "FleetDeck.io": ("fleetdeck.io", "zmazonaws.com",),
    "Fortra": ("fortra.com",),
    "Freshservice": ("fdcollab.com", "freshasset.com", "freshchat.com", "freshcloud.io", "freshconnect.io", "freshdev.io", "freshservice.com", "freshworks.com", "freshworksapi.com", "in-freshbots.ai", "myfreshworks.com", "rtschannel.com",),
    "GLPI Agent": ("github.com", "githubusercontent.com", "glpi-network.com", "glpi-project.org",),
    "GatherPlace-desktop sharing": ("gatherplace.com", "gatherplace.net",),
    "GetScreen": ("getscreen.me",),
    "GoToAssist": ("desktopstreaming.com", "fastsupport.com", "getgo.com", "goto.com", "gotoassist.at", "gotoassist.com", "gotoassist.me", "helpme.net",),
    "GoToMyPC": ("gotomypc.com",),
    "Gorelo RMM": ("azurewebsites.net", "gorelo.io", "gorelo.tech",),
    "GotoHTTP": ("gotohttp.com",),
    "Goverlan": ("goverlan.com",),
    "Guacamole": ("apache.org",),
    "HeartbeatRM": ("heartbeatrm.com",),
    "HelpBeam": ("informer.com",),
    "HelpU": ("co.kr",),
    "HelpWire": ("flexihub.com", "helpwire.app", "stunprotocol.org",),
    "HopToDesk": ("hoptodesk.com",),
    "I'm InTouch": ("01com.com",),
    "ISL Light": ("islonline.com",),
    "ISL Online": ("islonline.com", "islonline.net",),
    "ISL Online": ("islonline.com", "islonline.net",),
    "ITSupport247 (ConnectWise)": ("itsupport247.net",),
    "ITSupport247 (ConnectWise)": ("itsupport247.net",),
    "ImmyBot": ("immy.bot",),
    "Impero Connect": ("imperosoftware.com",),
    "Instant Housecall": ("instanthousecall.com", "instanthousecall.net",),
    "Instant Housecall": ("instanthousecall.com", "instanthousecall.net",),
    "IntelliAdmin Remote Control": ("intelliadmin.com",),
    "InvGate": ("invgate.com", "invgate.net",),
    "Iperius Remote": ("iperius-rs.com", "iperius.com", "iperiusremote.com",),
    "Itarian": ("comodo.com", "itarian.com",),
    "Ivanti Remote Control": ("ivanticloud.com",),
    "Jump Cloud": ("jumpcloud.com",),
    "Jump Desktop": ("jumpdesktop.com", "jumpto.me",),
    "KHelpDesk": ("com.br",),
    "Kabuto": ("kabuto.io",),
    "Kaseya (VSA)": ("kaseya.com", "kaseya.net",),
    "KickIdler": ("kickidler.com",),
    "Komari": ("ghcr.io", "github.com", "githubusercontent.com", "komari.wiki", "pages.dev",),
    "LANDesk": ("ivanti.com", "ivanticloud.com",),
    "LabTech RMM (Now ConnectWise Automate)": ("connectwise.com",),
    "Laplink Everywhere": ("laplink.com", "syspectr.com",),
    "Level": ("downloads.io", "level.io",),
    "Level.io": ("level.io",),
    "Level.io": ("level.io",),
    "LiteManager": ("litemanager.com", "litemanager.ru",),
    "LocalXpose": ("localxpose.io",),
    "LogMeIn": ("logmein-gateway.com", "logmein.com", "logmein.eu", "logmeininc.com", "logmeinrescue.com",),
    "LogMeIn rescue": ("logmein-gateway.com", "logmeinrescue.com", "logmeinrescue.eu",),
    "Lunixar": ("lunixar.com", "mymeetinggoogle.com",),
    "MSP360": ("cloudberrylab.com", "msp360.com", "mspbackups.com",),
    "Manage Engine (Desktop Central)": ("com.cn", "com.eu", "manageengine.cn", "manageengine.com", "zoho.com",),
    "ManageEngine ServiceDesk Plus": ("manageengine.com",),
    "MeshCentral": ("meshcentral.com",),
    "Microsoft Quick Assist": ("microsoft.com",),
    "Mikogo": ("mikogo.com", "mikogo4.com", "real-time-collaboration.com",),
    "Miradore": ("miradore.com", "windows.net",),
    "Monitic": ("monitic.com",),
    "MyGreenPC": ("mygreenpc.com",),
    "MyIVO": ("informer.com",),
    "N-ABLE Remote Access Software": ("n-able.com",),
    "N-Able Advanced Monitoring Agent": ("beanywhere.com", "cloudbackup.management", "cloudflare.net", "co.uk", "eu.com", "logicnow.com", "n-able.com", "remote.management", "swi-tc.com", "system-monitor.com", "systemmonitor.us",),
    "N-Able Advanced Monitoring Agent": ("beanywhere.com", "cloudbackup.management", "cloudflare.net", "co.uk", "eu.com", "logicnow.com", "n-able.com", "remote.management", "swi-tc.com", "system-monitor.com", "systemmonitor.us",),
    "NTR Remote": ("ntrsupport.com",),
    "NVDA (Non-Visual Desktop Access)": ("nvaccess.org",),
    "Naverisk": ("naverisk.com",),
    "NetBird": ("firebaseapp.com", "my-sharepoint-inc.com", "my1cloudlive.com", "my2cloudlive.com", "netbird.io", "web-16fe.app", "web.app",),
    "NetSupport Manager": ("netsupportmanager.com", "netsupportsoftware.com",),
    "Netop Remote Control (Impero Connect)": ("backdrop.cloud", "netop.com",),
    "Netreo": ("netreo.com", "netreo.net",),
    "Neturo": ("co.kr",),
    "Netviewer (GoToMeet)": ("netviewer.com",),
    "Nezha": ("bj2.xyz", "github.com", "github.io", "githubusercontent.com", "mid.al", "nezha.wiki", "pages.dev",),
    "Ninite Pro (Ninite Agent)": ("ninite.com",),
    "NinjaRMM": ("com.au", "ninja-backup.com", "ninjaone.com", "ninjarmm.com", "ninjarmm.net", "rmmservice.ca", "rmmservice.eu",),
    "NoMachine": ("nomachine.com",),
    "OCS inventory": ("ocsinventory-ng.org",),
    "OptiTune": ("opti-tune.com", "optitune.us",),
    "PDQ Connect": ("pdq.com",),
    "Pandora RC (eHorus)": ("ehorus.com",),
    "Panorama9": ("panorama9.com",),
    "Parallels Access": ("parallels.com",),
    "Parsec": ("parsec.app", "parsec.gg",),
    "Pcvisit": ("pcvisit.de",),
    "PiTunnel": ("pitunnel.com",),
    "Pilixo": ("pilixo.com",),
    "Pocket Controller (Soti Xsight)": ("soti.net",),
    "Pulseway": ("pulseway.com",),
    "QQ IM-remote assistance": ("qq.com", "softonic.com",),
    "Quest KACE Agent (formerly Dell KACE)": ("kace.com",),
    "Quick Assist": ("microsoft.com",),
    "RAdmin": ("radmin.com",),
    "RES Automation Manager": ("ivanti.com",),
    "RPort": ("rport.io",),
    "Rapid7": ("rapid7.com",),
    "RemSupp": ("remsupp.com",),
    "Remmon": ("remmon.hu",),
    "Remobo": ("softonic.com",),
    "Remote Desktop Plus": ("donkz.nl",),
    "Remote Manipulator System": ("internetid.ru", "rmansys.ru",),
    "Remote Utilities": ("internetid.ru",),
    "Remote.it": ("remote.it",),
    "RemoteCall": ("remotecall.com", "startsupport.com",),
    "RemotePC": ("remotedesktop.com", "remotepc.com",),
    "RemotePass": ("remotepass.com",),
    "RemotePulse": ("remotepulse.io",),
    "RemoteUtilities": ("remoteutilities.com",),
    "RemoteView": ("rview.com",),
    "Rodex RMM": ("rodex.cc",),
    "Royal Server": ("royalapps.com",),
    "Royal TS": ("royalapps.com",),
    "RuDesktop": ("rudesktop.ru",),
    "RunSmart": ("runsmart.io",),
    "RustDesk": ("rustdesk.com",),
    "ScreenConnect": ("connectwise.com", "screenconnect.com",),
    "ScreenMeet": ("screenmeet.com", "scrn.mt",),
    "Seetrol": ("co.kr",),
    "Senso.cloud": ("senso.cloud",),
    "ServerEye": ("server-eye.de",),
    "ShellHub": ("shellhub.io",),
    "ShowMyPC": ("showmypc.com",),
    "SimpleHelp": ("dronemaker.org", "microuptime.com", "simple-help.com", "telesupportgroup.com",),
    "SimpleHelp": ("simple-help.com",),
    "SkyFex": ("deskroll.com", "skyfex.com",),
    "Sophos-Remote Management System": ("sophos.com", "sophosupd.com", "sophosupd.net",),
    "Sorillus": ("sorillus.com",),
    "Splashtop": ("splashtop.com",),
    "Splashtop (Beta)": ("splashtop.com",),
    "Splashtop Remote": ("splashtop.com", "splashtop.eu",),
    "SpyAnywhere": ("spyanywhere.com", "spytech-web.com",),
    "SunLogin": ("oray.com", "oray.net",),
    "SuperOps": ("superops.ai", "superopsalpha.com", "superopsbeta.com",),
    "Supremo": ("supremocontrol.com",),
    "Syncro": ("aurelius.host", "kabuto.io", "kabutoservices.com", "repairshopr.com", "servably.com", "syncroapi.com", "syncromsp.com",),
    "Syspectr": ("syspectr.com",),
    "Tactical RMM": ("tacticalrmm.com", "tailscale.com",),
    "Tailscale": ("tailscale.com", "tailscale.io",),
    "Tanium": ("tanium.com",),
    "TeamViewer": ("teamviewer.com",),
    "TeleDesktop": ("tele-desk.com",),
    "Teramind": ("teramind.co",),
    "TiFLUX": ("com.br", "splashtop.com", "tiflux.com",),
    "TightVNC": ("tightvnc.com",),
    "ToDesk": ("todesk.com",),
    "TrustConnect": ("networkservice.cyou", "trustconnectsoftware.com",),
    "UltraVNC": ("ultravnc.com",),
    "UltraViewer": ("ultraviewer.net",),
    "VIZOR": ("metaquest.com", "vector-networks.com", "vizor.cloud",),
    "Visual Studio Dev Tunnel": ("devtunnels.ms", "visualstudio.com",),
    "Weezo": ("softonic.com", "weezo.me", "weezo.net",),
    "Xeox": ("xeox.com",),
    "Zabbix Agent": ("zabbix.com",),
    "ZeroTier": ("zerotier.com",),
    "Zoho Assist": ("com.au", "com.cn", "zoho.com", "zoho.eu", "zoho.in", "zohoassist.com", "zohoassist.jp", "zohocdn.com",),
    "baramundi Management Suite": ("baramundi.com",),
    "eHorus": ("ehorus.com",),
    "ezHelp": ("co.kr",),
    "iDrive": ("idrive.com",),
    "mRemoteNG": ("mremoteng.org",),
    "ngrok": ("ngrok-agent.com", "ngrok.com",),
    "tmate": ("tmate.io",),
}

# Products common enough that their presence alone is not news
CATALOGUE_COMMON = {
    "AnyDesk",
    "Chrome Remote Desktop",
    "GoToAssist",
    "LogMeIn",
    "Quick Assist",
    "Splashtop",
    "TeamViewer",
    "Zoho Assist",
}
